name: React CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # compulsory step: official GitHub action to check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # optional step: set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm test -- --watchAll=false

      - name: Build app
        run: npm run build
